var searchData=
[
  ['back_5finsert_5fiterator',['back_insert_iterator',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06620.html',1,'std']]],
  ['bad_5falloc',['bad_alloc',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01660.html',1,'std']]],
  ['bad_5fany_5fcast',['bad_any_cast',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08888.html',1,'std::experimental::fundamentals_v1']]],
  ['bad_5fcast',['bad_cast',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01676.html',1,'std']]],
  ['bad_5fexception',['bad_exception',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01652.html',1,'std']]],
  ['bad_5ffunction_5fcall',['bad_function_call',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06168.html',1,'std']]],
  ['bad_5foptional_5faccess',['bad_optional_access',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09000.html',1,'std::experimental::fundamentals_v1']]],
  ['bad_5ftypeid',['bad_typeid',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01680.html',1,'std']]],
  ['bad_5fweak_5fptr',['bad_weak_ptr',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05976.html',1,'std']]],
  ['balanced_5fquicksort_5ftag',['balanced_quicksort_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08684.html',1,'__gnu_parallel']]],
  ['balanced_5ftag',['balanced_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08640.html',1,'__gnu_parallel']]],
  ['balanceutilities',['BalanceUtilities',['../../../samrai/2.4.4/html/structSAMRAI_1_1mesh_1_1BalanceUtilities.html',1,'SAMRAI::mesh']]],
  ['basegriddingalgorithm',['BaseGriddingAlgorithm',['../../../samrai/2.4.4/html/classSAMRAI_1_1mesh_1_1BaseGriddingAlgorithm.html',1,'SAMRAI::mesh']]],
  ['basepatchhierarchy',['BasePatchHierarchy',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1BasePatchHierarchy.html',1,'SAMRAI::hier']]],
  ['basepatchlevel',['BasePatchLevel',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1BasePatchLevel.html',1,'SAMRAI::hier']]],
  ['bases',['bases',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08740.html',1,'std::tr2']]],
  ['basic_5fbranch',['basic_branch',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10032.html',1,'__gnu_pbds']]],
  ['basic_5fbranch_3c_20key_2c_20mapped_2c_20tag_2c_20detail_3a_3atree_5ftraits_3c_20key_2c_20mapped_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20tag_2c_20_5falloc_20_3e_3a_3anode_5fupdate_2c_20_5f_5fgnu_5fcxx_3a_3atypelist_3a_3acreate2_3c_20cmp_5ffn_2c_20detail_3a_3atree_5ftraits_3c_20key_2c_20mapped_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20tag_2c_20_5falloc_20_3e_20_3e_3a_3atype_2c_20_5falloc_20_3e',['basic_branch&lt; Key, Mapped, Tag, detail::tree_traits&lt; Key, Mapped, Cmp_Fn, Node_Update, Tag, _Alloc &gt;::node_update, __gnu_cxx::typelist::create2&lt; Cmp_Fn, detail::tree_traits&lt; Key, Mapped, Cmp_Fn, Node_Update, Tag, _Alloc &gt; &gt;::type, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10032.html',1,'']]],
  ['basic_5fbranch_3c_20key_2c_20mapped_2c_20tag_2c_20detail_3a_3atrie_5ftraits_3c_20key_2c_20mapped_2c_20_5fatraits_2c_20node_5fupdate_2c_20tag_2c_20_5falloc_20_3e_3a_3anode_5fupdate_2c_20_5f_5fgnu_5fcxx_3a_3atypelist_3a_3acreate2_3c_20_5fatraits_2c_20detail_3a_3atrie_5ftraits_3c_20key_2c_20mapped_2c_20_5fatraits_2c_20node_5fupdate_2c_20tag_2c_20_5falloc_20_3e_20_3e_3a_3atype_2c_20_5falloc_20_3e',['basic_branch&lt; Key, Mapped, Tag, detail::trie_traits&lt; Key, Mapped, _ATraits, Node_Update, Tag, _Alloc &gt;::node_update, __gnu_cxx::typelist::create2&lt; _ATraits, detail::trie_traits&lt; Key, Mapped, _ATraits, Node_Update, Tag, _Alloc &gt; &gt;::type, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10032.html',1,'']]],
  ['basic_5fbranch_5ftag',['basic_branch_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10156.html',1,'__gnu_pbds']]],
  ['basic_5ffilebuf',['basic_filebuf',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02072.html',1,'std']]],
  ['basic_5ffilebuf_3c_20_5fchart_2c_20encoding_5fchar_5ftraits_3c_20_5fchart_20_3e_20_3e',['basic_filebuf&lt; _CharT, encoding_char_traits&lt; _CharT &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02072.html',1,'']]],
  ['basic_5ffilebuf_3c_20char_5ftype_2c_20traits_5ftype_20_3e',['basic_filebuf&lt; char_type, traits_type &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02072.html',1,'']]],
  ['basic_5ffstream',['basic_fstream',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02084.html',1,'std']]],
  ['basic_5fhash_5ftable',['basic_hash_table',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10020.html',1,'__gnu_pbds']]],
  ['basic_5fhash_5ftable_3c_20key_2c_20mapped_2c_20hash_5ffn_2c_20eq_5ffn_2c_20resize_5fpolicy_2c_20store_5fhash_2c_20cc_5fhash_5ftag_2c_20_5f_5fgnu_5fcxx_3a_3atypelist_3a_3acreate1_3c_20comb_5fhash_5ffn_20_3e_3a_3atype_2c_20_5falloc_20_3e',['basic_hash_table&lt; Key, Mapped, Hash_Fn, Eq_Fn, Resize_Policy, Store_Hash, cc_hash_tag, __gnu_cxx::typelist::create1&lt; Comb_Hash_Fn &gt;::type, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10020.html',1,'']]],
  ['basic_5fhash_5ftable_3c_20key_2c_20mapped_2c_20hash_5ffn_2c_20eq_5ffn_2c_20resize_5fpolicy_2c_20store_5fhash_2c_20gp_5fhash_5ftag_2c_20_5f_5fgnu_5fcxx_3a_3atypelist_3a_3acreate2_3c_20comb_5fprobe_5ffn_2c_20probe_5ffn_20_3e_3a_3atype_2c_20_5falloc_20_3e',['basic_hash_table&lt; Key, Mapped, Hash_Fn, Eq_Fn, Resize_Policy, Store_Hash, gp_hash_tag, __gnu_cxx::typelist::create2&lt; Comb_Probe_Fn, Probe_Fn &gt;::type, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10020.html',1,'']]],
  ['basic_5fhash_5ftag',['basic_hash_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10144.html',1,'__gnu_pbds']]],
  ['basic_5fifstream',['basic_ifstream',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02076.html',1,'std']]],
  ['basic_5finvalidation_5fguarantee',['basic_invalidation_guarantee',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10116.html',1,'__gnu_pbds']]],
  ['basic_5fios',['basic_ios',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02564.html',1,'std']]],
  ['basic_5fios_3c_20char_2c_20_5ftraits_20_3e',['basic_ios&lt; char, _Traits &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02564.html',1,'']]],
  ['basic_5fiostream',['basic_iostream',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02580.html',1,'std']]],
  ['basic_5fiostream_3c_20char_20_3e',['basic_iostream&lt; char &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02580.html',1,'']]],
  ['basic_5fistream',['basic_istream',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02572.html',1,'std']]],
  ['basic_5fistream_3c_20char_20_3e',['basic_istream&lt; char &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02572.html',1,'']]],
  ['basic_5fistream_3c_20char_2c_20_5ftraits_20_3e',['basic_istream&lt; char, _Traits &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02572.html',1,'']]],
  ['basic_5fistringstream',['basic_istringstream',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02588.html',1,'std']]],
  ['basic_5fofstream',['basic_ofstream',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02080.html',1,'std']]],
  ['basic_5fostream',['basic_ostream',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02576.html',1,'std']]],
  ['basic_5fostream_3c_20char_20_3e',['basic_ostream&lt; char &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02576.html',1,'']]],
  ['basic_5fostream_3c_20char_2c_20_5ftraits_20_3e',['basic_ostream&lt; char, _Traits &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02576.html',1,'']]],
  ['basic_5fostringstream',['basic_ostringstream',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02592.html',1,'std']]],
  ['basic_5fregex',['basic_regex',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05780.html',1,'std']]],
  ['basic_5fstreambuf',['basic_streambuf',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02568.html',1,'std']]],
  ['basic_5fstreambuf_3c_20_5felem_2c_20_5ftr_20_3e',['basic_streambuf&lt; _Elem, _Tr &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02568.html',1,'']]],
  ['basic_5fstreambuf_3c_20char_2c_20_5ftraits_20_3e',['basic_streambuf&lt; char, _Traits &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02568.html',1,'']]],
  ['basic_5fstreambuf_3c_20char_2c_20char_5ftraits_3c_20char_20_3e_20_3e',['basic_streambuf&lt; char, char_traits&lt; char &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02568.html',1,'']]],
  ['basic_5fstring',['basic_string',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03900.html',1,'std']]],
  ['basic_5fstring',['basic_string',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07800.html',1,'__gnu_debug']]],
  ['basic_5fstring_3c_20_5fchart_20_3e',['basic_string&lt; _CharT &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03900.html',1,'']]],
  ['basic_5fstring_3c_20_5fchart_2c_20_5ftraits_2c_20_5fallocator_20_3e',['basic_string&lt; _CharT, _Traits, _Allocator &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03900.html',1,'']]],
  ['basic_5fstring_3c_20_5felem_2c_20char_5ftraits_3c_20_5felem_20_3e_2c_20_5fwide_5falloc_20_3e',['basic_string&lt; _Elem, char_traits&lt; _Elem &gt;, _Wide_alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03900.html',1,'']]],
  ['basic_5fstring_3c_20char_20_3e',['basic_string&lt; char &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03900.html',1,'']]],
  ['basic_5fstring_3c_20char_2c_20char_5ftraits_3c_20char_20_3e_2c_20_5fbyte_5falloc_20_3e',['basic_string&lt; char, char_traits&lt; char &gt;, _Byte_alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03900.html',1,'']]],
  ['basic_5fstring_3c_20char_5ftype_2c_20_5ftraits_2c_20_5falloc_20_3e',['basic_string&lt; char_type, _Traits, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03900.html',1,'']]],
  ['basic_5fstring_3c_20value_5ftype_20_3e',['basic_string&lt; value_type &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03900.html',1,'']]],
  ['basic_5fstring_5fview',['basic_string_view',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09092.html',1,'std::experimental::fundamentals_v1']]],
  ['basic_5fstringbuf',['basic_stringbuf',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02584.html',1,'std']]],
  ['basic_5fstringstream',['basic_stringstream',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02596.html',1,'std']]],
  ['bergerrigoutsos',['BergerRigoutsos',['../../../samrai/2.4.4/html/classSAMRAI_1_1mesh_1_1BergerRigoutsos.html',1,'SAMRAI::mesh']]],
  ['bernoulli_5fdistribution',['bernoulli_distribution',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05496.html',1,'std']]],
  ['bgaussseidelpreconditioner',['BGaussSeidelPreconditioner',['../class_i_b_t_k_1_1_b_gauss_seidel_preconditioner.html',1,'IBTK']]],
  ['bidirectional_5fiterator_5ftag',['bidirectional_iterator_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06664.html',1,'std']]],
  ['bin_5fsearch_5ftree_5fconst_5fit_5f',['bin_search_tree_const_it_',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10556.html',1,'__gnu_pbds::detail']]],
  ['bin_5fsearch_5ftree_5fconst_5fnode_5fit_5f',['bin_search_tree_const_node_it_',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10548.html',1,'__gnu_pbds::detail']]],
  ['bin_5fsearch_5ftree_5fit_5f',['bin_search_tree_it_',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10560.html',1,'__gnu_pbds::detail']]],
  ['bin_5fsearch_5ftree_5fnode_5fit_5f',['bin_search_tree_node_it_',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10552.html',1,'__gnu_pbds::detail']]],
  ['bin_5fsearch_5ftree_5ftraits',['bin_search_tree_traits',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10564.html',1,'__gnu_pbds::detail']]],
  ['bin_5fsearch_5ftree_5ftraits_3c_20key_2c_20mapped_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20rb_5ftree_5fnode_5f_3c_20types_5ftraits_3c_20key_2c_20mapped_2c_20_5falloc_2c_20false_20_3e_3a_3avalue_5ftype_2c_20tree_5fnode_5fmetadata_5fdispatch_3c_20key_2c_20mapped_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20_5falloc_20_3e_3a_3atype_2c_20_5falloc_20_3e_2c_20_5falloc_20_3e',['bin_search_tree_traits&lt; Key, Mapped, Cmp_Fn, Node_Update, rb_tree_node_&lt; types_traits&lt; Key, Mapped, _Alloc, false &gt;::value_type, tree_node_metadata_dispatch&lt; Key, Mapped, Cmp_Fn, Node_Update, _Alloc &gt;::type, _Alloc &gt;, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10564.html',1,'']]],
  ['bin_5fsearch_5ftree_5ftraits_3c_20key_2c_20mapped_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20splay_5ftree_5fnode_5f_3c_20types_5ftraits_3c_20key_2c_20mapped_2c_20_5falloc_2c_20false_20_3e_3a_3avalue_5ftype_2c_20tree_5fnode_5fmetadata_5fdispatch_3c_20key_2c_20mapped_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20_5falloc_20_3e_3a_3atype_2c_20_5falloc_20_3e_2c_20_5falloc_20_3e',['bin_search_tree_traits&lt; Key, Mapped, Cmp_Fn, Node_Update, splay_tree_node_&lt; types_traits&lt; Key, Mapped, _Alloc, false &gt;::value_type, tree_node_metadata_dispatch&lt; Key, Mapped, Cmp_Fn, Node_Update, _Alloc &gt;::type, _Alloc &gt;, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10564.html',1,'']]],
  ['bin_5fsearch_5ftree_5ftraits_3c_20key_2c_20null_5ftype_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20node_2c_20_5falloc_20_3e',['bin_search_tree_traits&lt; Key, null_type, Cmp_Fn, Node_Update, Node, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10568.html',1,'__gnu_pbds::detail']]],
  ['bin_5fsearch_5ftree_5ftraits_3c_20key_2c_20null_5ftype_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20rb_5ftree_5fnode_5f_3c_20types_5ftraits_3c_20key_2c_20null_5ftype_2c_20_5falloc_2c_20false_20_3e_3a_3avalue_5ftype_2c_20tree_5fnode_5fmetadata_5fdispatch_3c_20key_2c_20null_5ftype_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20_5falloc_20_3e_3a_3atype_2c_20_5falloc_20_3e_2c_20_5falloc_20_3e',['bin_search_tree_traits&lt; Key, null_type, Cmp_Fn, Node_Update, rb_tree_node_&lt; types_traits&lt; Key, null_type, _Alloc, false &gt;::value_type, tree_node_metadata_dispatch&lt; Key, null_type, Cmp_Fn, Node_Update, _Alloc &gt;::type, _Alloc &gt;, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10564.html',1,'']]],
  ['bin_5fsearch_5ftree_5ftraits_3c_20key_2c_20null_5ftype_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20splay_5ftree_5fnode_5f_3c_20types_5ftraits_3c_20key_2c_20null_5ftype_2c_20_5falloc_2c_20false_20_3e_3a_3avalue_5ftype_2c_20tree_5fnode_5fmetadata_5fdispatch_3c_20key_2c_20null_5ftype_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20_5falloc_20_3e_3a_3atype_2c_20_5falloc_20_3e_2c_20_5falloc_20_3e',['bin_search_tree_traits&lt; Key, null_type, Cmp_Fn, Node_Update, splay_tree_node_&lt; types_traits&lt; Key, null_type, _Alloc, false &gt;::value_type, tree_node_metadata_dispatch&lt; Key, null_type, Cmp_Fn, Node_Update, _Alloc &gt;::type, _Alloc &gt;, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10564.html',1,'']]],
  ['binary_5fcompose',['binary_compose',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08088.html',1,'__gnu_cxx']]],
  ['binary_5ffunction',['binary_function',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'std']]],
  ['binary_5ffunction_3c_20_5f_5fshared_5fptr_3c_20_5ftp_2c_20_5flp_20_3e_2c_20_5f_5fshared_5fptr_3c_20_5ftp_2c_20_5flp_20_3e_2c_20bool_20_3e',['binary_function&lt; __shared_ptr&lt; _Tp, _Lp &gt;, __shared_ptr&lt; _Tp, _Lp &gt;, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20_5f_5fweak_5fptr_3c_20_5ftp_2c_20_5flp_20_3e_2c_20_5f_5fweak_5fptr_3c_20_5ftp_2c_20_5flp_20_3e_2c_20bool_20_3e',['binary_function&lt; __weak_ptr&lt; _Tp, _Lp &gt;, __weak_ptr&lt; _Tp, _Lp &gt;, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20_5farg1_2c_20_5farg2_2c_20_5farg1_20_3e',['binary_function&lt; _Arg1, _Arg2, _Arg1 &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20_5farg1_2c_20_5farg2_2c_20_5farg2_20_3e',['binary_function&lt; _Arg1, _Arg2, _Arg2 &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20_5fpredicate_3a_3afirst_5fargument_5ftype_2c_20_5fpredicate_3a_3asecond_5fargument_5ftype_2c_20bool_20_3e',['binary_function&lt; _Predicate::first_argument_type, _Predicate::second_argument_type, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20_5fsp_2c_20_5fsp_2c_20bool_20_3e',['binary_function&lt; _Sp, _Sp, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20_5ft1_20_2a_2c_20_5ft2_2c_20_5fres_20_3e',['binary_function&lt; _T1 *, _T2, _Res &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20_5ft1_2c_20_5ft2_2c_20_5fres_20_3e',['binary_function&lt; _T1, _T2, _Res &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20_5ft1_2c_20_5ft2_2c_20bool_20_3e',['binary_function&lt; _T1, _T2, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20_5ftp_20_2a_2c_20_5farg_2c_20_5fret_20_3e',['binary_function&lt; _Tp *, _Arg, _Ret &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20_5ftp_2c_20_5farg_2c_20_5fret_20_3e',['binary_function&lt; _Tp, _Arg, _Ret &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20_5ftp_2c_20_5ftp_2c_20_5ftp_20_3e',['binary_function&lt; _Tp, _Tp, _Tp &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20_5ftp_2c_20_5ftp_2c_20bool_20_3e',['binary_function&lt; _Tp, _Tp, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20_5ftp1_2c_20_5ftp2_2c_20_5fresult_20_3e',['binary_function&lt; _Tp1, _Tp2, _Result &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20const_20_5ft1_20_2a_2c_20_5ft2_2c_20_5fres_20_3e',['binary_function&lt; const _T1 *, _T2, _Res &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20const_20_5ftp_20_2a_2c_20_5farg_2c_20_5fret_20_3e',['binary_function&lt; const _Tp *, _Arg, _Ret &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20const_20elempatchitem_20_26_2c_20const_20elempatchitem_20_26_2c_20bool_20_3e',['binary_function&lt; const ElemPatchItem &amp;, const ElemPatchItem &amp;, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'std']]],
  ['binary_5ffunction_3c_20const_20libmesh_3a_3adofobject_20_2aconst_2c_20const_20libmesh_3a_3adofobject_20_2aconst_2c_20bool_20_3e',['binary_function&lt; const libMesh::DofObject *const, const libMesh::DofObject *const, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'std']]],
  ['binary_5ffunction_3c_20const_20lnodeindex_20_26_2c_20const_20lnodeindex_20_26_2c_20bool_20_3e',['binary_function&lt; const LNodeIndex &amp;, const LNodeIndex &amp;, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'std']]],
  ['binary_5ffunction_3c_20const_20lnodeindex_20_2a_2c_20const_20lnodeindex_20_2a_2c_20bool_20_3e',['binary_function&lt; const LNodeIndex *, const LNodeIndex *, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'std']]],
  ['binary_5ffunction_3c_20const_20volatile_20_5ft1_20_2a_2c_20_5ft2_2c_20_5fres_20_3e',['binary_function&lt; const volatile _T1 *, _T2, _Res &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20edge_2c_20edge_2c_20bool_20_3e',['binary_function&lt; Edge, Edge, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'std']]],
  ['binary_5ffunction_3c_20rope_3c_20_5fchart_2c_20_5falloc_20_3e_2c_20rope_3c_20_5fchart_2c_20_5falloc_20_3e_2c_20rope_3c_20_5fchart_2c_20_5falloc_20_3e_20_3e',['binary_function&lt; rope&lt; _CharT, _Alloc &gt;, rope&lt; _CharT, _Alloc &gt;, rope&lt; _CharT, _Alloc &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20samrai_3a_3ahier_3a_3aindex_3c_20ndim_20_3e_2c_20samrai_3a_3ahier_3a_3aindex_3c_20ndim_20_3e_2c_20bool_20_3e',['binary_function&lt; SAMRAI::hier::Index&lt; NDIM &gt;, SAMRAI::hier::Index&lt; NDIM &gt;, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'std']]],
  ['binary_5ffunction_3c_20samrai_3a_3apdat_3a_3acellindex_3c_20ndim_20_3e_2c_20samrai_3a_3apdat_3a_3acellindex_3c_20ndim_20_3e_2c_20bool_20_3e',['binary_function&lt; SAMRAI::pdat::CellIndex&lt; NDIM &gt;, SAMRAI::pdat::CellIndex&lt; NDIM &gt;, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'std']]],
  ['binary_5ffunction_3c_20shared_5fptr_3c_20_5ftp_20_3e_2c_20shared_5fptr_3c_20_5ftp_20_3e_2c_20bool_20_3e',['binary_function&lt; shared_ptr&lt; _Tp &gt;, shared_ptr&lt; _Tp &gt;, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20std_3a_3apair_3c_20_5ft1_2c_20_5ft2_20_3e_2c_20std_3a_3apair_3c_20_5ft1_2c_20_5ft2_20_3e_2c_20bool_20_3e',['binary_function&lt; std::pair&lt; _T1, _T2 &gt;, std::pair&lt; _T1, _T2 &gt;, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20value_5ftype_2c_20value_5ftype_2c_20bool_20_3e',['binary_function&lt; value_type, value_type, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20void_2c_20void_2c_20bool_20_3e',['binary_function&lt; void, void, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20volatile_20_5ft1_20_2a_2c_20_5ft2_2c_20_5fres_20_3e',['binary_function&lt; volatile _T1 *, _T2, _Res &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20weak_5fptr_3c_20_5ftp_20_3e_2c_20weak_5fptr_3c_20_5ftp_20_3e_2c_20bool_20_3e',['binary_function&lt; weak_ptr&lt; _Tp &gt;, weak_ptr&lt; _Tp &gt;, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5fheap',['binary_heap',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10488.html',1,'__gnu_pbds::detail']]],
  ['binary_5fheap_5fconst_5fiterator_5f',['binary_heap_const_iterator_',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10492.html',1,'__gnu_pbds::detail']]],
  ['binary_5fheap_5fpoint_5fconst_5fiterator_5f',['binary_heap_point_const_iterator_',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10528.html',1,'__gnu_pbds::detail']]],
  ['binary_5fheap_5ftag',['binary_heap_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10204.html',1,'__gnu_pbds']]],
  ['binary_5fnegate',['binary_negate',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06556.html',1,'std']]],
  ['binarytree',['BinaryTree',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1BinaryTree.html',1,'SAMRAI::hier']]],
  ['binder1st',['binder1st',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07452.html',1,'std']]],
  ['binder2nd',['binder2nd',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07456.html',1,'std']]],
  ['binomial_5fdistribution',['binomial_distribution',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05504.html',1,'std']]],
  ['binomial_5fheap',['binomial_heap',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10536.html',1,'__gnu_pbds::detail']]],
  ['binomial_5fheap_5fbase',['binomial_heap_base',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10540.html',1,'__gnu_pbds::detail']]],
  ['binomial_5fheap_5ftag',['binomial_heap_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10196.html',1,'__gnu_pbds']]],
  ['bitmap_5fallocator',['bitmap_allocator',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09212.html',1,'__gnu_cxx']]],
  ['bitset',['bitset',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07756.html',1,'std::__debug']]],
  ['bitset',['bitset',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01816.html',1,'std']]],
  ['bitset',['bitset',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08024.html',1,'std::__profile']]],
  ['bjacobipreconditioner',['BJacobiPreconditioner',['../class_i_b_t_k_1_1_b_jacobi_preconditioner.html',1,'IBTK']]],
  ['blockgridgeometry',['BlockGridGeometry',['../../../samrai/2.4.4/html/classSAMRAI_1_1geom_1_1BlockGridGeometry.html',1,'SAMRAI::geom']]],
  ['blockpatchgeometry',['BlockPatchGeometry',['../../../samrai/2.4.4/html/classSAMRAI_1_1geom_1_1BlockPatchGeometry.html',1,'SAMRAI::geom']]],
  ['bool_5fset',['bool_set',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08704.html',1,'std::tr2']]],
  ['boundarybox',['BoundaryBox',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1BoundaryBox.html',1,'SAMRAI::hier']]],
  ['boundaryboxutils',['BoundaryBoxUtils',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1BoundaryBoxUtils.html',1,'SAMRAI::hier']]],
  ['boundarylookuptable',['BoundaryLookupTable',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1BoundaryLookupTable.html',1,'SAMRAI::hier']]],
  ['boundarynode',['BoundaryNode',['../../../samrai/2.4.4/html/classSAMRAI_1_1appu_1_1BoundaryNode.html',1,'SAMRAI::appu']]],
  ['boundaryutilitystrategy',['BoundaryUtilityStrategy',['../../../samrai/2.4.4/html/classSAMRAI_1_1appu_1_1BoundaryUtilityStrategy.html',1,'SAMRAI::appu']]],
  ['box',['Box',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1Box.html',1,'SAMRAI::hier']]],
  ['box_3c_20ndim_20_3e',['Box&lt; NDIM &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1Box.html',1,'SAMRAI::hier']]],
  ['boxarray',['BoxArray',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1BoxArray.html',1,'SAMRAI::hier']]],
  ['boxcomm',['BoxComm',['../../../samrai/2.4.4/html/structSAMRAI_1_1hier_1_1BoxComm.html',1,'SAMRAI::hier']]],
  ['boxgeneratorstrategy',['BoxGeneratorStrategy',['../../../samrai/2.4.4/html/classSAMRAI_1_1mesh_1_1BoxGeneratorStrategy.html',1,'SAMRAI::mesh']]],
  ['boxgeometry',['BoxGeometry',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1BoxGeometry.html',1,'SAMRAI::hier']]],
  ['boxgeometryfillpattern',['BoxGeometryFillPattern',['../../../samrai/2.4.4/html/classSAMRAI_1_1xfer_1_1BoxGeometryFillPattern.html',1,'SAMRAI::xfer']]],
  ['boxgraph',['BoxGraph',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1BoxGraph.html',1,'SAMRAI::hier']]],
  ['boxgraphutilities',['BoxGraphUtilities',['../../../samrai/2.4.4/html/structSAMRAI_1_1hier_1_1BoxGraphUtilities.html',1,'SAMRAI::hier']]],
  ['boxioutility',['BoxIOUtility',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1BoxIOUtility.html',1,'SAMRAI::hier']]],
  ['boxiterator',['BoxIterator',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1BoxIterator.html',1,'SAMRAI::hier']]],
  ['boxlist',['BoxList',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1BoxList.html',1,'SAMRAI::hier']]],
  ['boxoverlap',['BoxOverlap',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1BoxOverlap.html',1,'SAMRAI::hier']]],
  ['boxtop',['BoxTop',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1BoxTop.html',1,'SAMRAI::hier']]],
  ['boxtree',['BoxTree',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1BoxTree.html',1,'SAMRAI::hier']]],
  ['boxtreenode',['BoxTreeNode',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1BoxTreeNode.html',1,'SAMRAI::hier']]],
  ['boxutilities',['BoxUtilities',['../../../samrai/2.4.4/html/structSAMRAI_1_1hier_1_1BoxUtilities.html',1,'SAMRAI::hier']]],
  ['branch_5fpolicy',['branch_policy',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10572.html',1,'__gnu_pbds::detail']]],
  ['branch_5fpolicy_3c_20node_5fcitr_2c_20node_5fcitr_2c_20_5falloc_20_3e',['branch_policy&lt; Node_CItr, Node_CItr, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10576.html',1,'__gnu_pbds::detail']]]
];
